version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1480681954
layout:
  /header/:
    -
      - 'logo-3397 30'
      - 'spacer-4878 70'
  /navigation/:
    -
      - menu-5914
  /main/:
    -
      - system-content-9682
  /footer/:
    -
      - position-footer
    -
      - 'copyright-4664 40'
      - 'spacer-3053 30'
      - 'branding-9102 30'
  offcanvas:
    -
      - mobile-menu-7165
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
