name: _body_only
timestamp: 1480681955
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1480681954
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-4011: 'System Messages'
  content:
    system-content-7964: 'Page Content'
inherit: {  }
