version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1480681954
layout:
  /main/:
    -
      - system-messages-4011
    -
      - system-content-7964
structure:
  main:
    attributes:
      boxed: ''
